version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - TestNetwork
    ports: 
      - 3000:3000
    depends_on: 
      - mysql_server
  
  mysql_server:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    networks: 
      - TestNetwork
    ports:
      - 3306:3306

networks:
  TestNetwork:
    driver: bridge
