FROM mysql:8.0

ENV MYSQL_DATABASE=meineDatenbank
ENV MYSQL_USER=wi22254
ENV MYSQL_PASSWORD=passwort
ENV MYSQL_ROOT_PASSWORD=admin

EXPOSE 3306

VOLUME [ "/var/lib/wi22254" ]

Copy ./init.sql /docker-entrypoint-initdb.d/init.sql
