version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=meineDatenbank
      - MYSQL_USER=wi22254
      - MYSQL_PASSWORD=passwort
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - /var/lib/wi22254
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql