version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - mysql_server
  
  mysql_server:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - 3306:3306

